<description>Debug support</description>
<groupName>DBG</groupName>
<addressBlock>
  <offset>0x0</offset>
  <size>0x400</size>
  <usage>registers</usage>
</addressBlock>
<registers>
  <register>
    <name>DBGMCU_IDCODE</name>
    <displayName>DBGMCU_IDCODE</displayName>
    <description>IDCODE</description>
    <addressOffset>0x0</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x10006411</resetValue>
    <fields>
      <field>
        <name>DEV_ID</name>
        <description>DEV_ID</description>
        <bitOffset>0</bitOffset>
        <bitWidth>12</bitWidth>
      </field>
      <field>
        <name>REV_ID</name>
        <description>REV_ID</description>
        <bitOffset>16</bitOffset>
        <bitWidth>16</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>DBGMCU_CR</name>
    <displayName>DBGMCU_CR</displayName>
    <description>Control Register</description>
    <addressOffset>0x4</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>DBG_SLEEP</name>
        <description>DBG_SLEEP</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_STOP</name>
        <description>DBG_STOP</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_STANDBY</name>
        <description>DBG_STANDBY</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>TRACE_IOEN</name>
        <description>TRACE_IOEN</description>
        <bitOffset>5</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>TRACE_MODE</name>
        <description>TRACE_MODE</description>
        <bitOffset>6</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DBG_I2C2_SMBUS_TIMEOUT</name>
        <description>DBG_I2C2_SMBUS_TIMEOUT</description>
        <bitOffset>16</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM8_STOP</name>
        <description>DBG_TIM8_STOP</description>
        <bitOffset>17</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM5_STOP</name>
        <description>DBG_TIM5_STOP</description>
        <bitOffset>18</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM6_STOP</name>
        <description>DBG_TIM6_STOP</description>
        <bitOffset>19</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM7_STOP</name>
        <description>DBG_TIM7_STOP</description>
        <bitOffset>20</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>DBGMCU_APB1_FZ</name>
    <displayName>DBGMCU_APB1_FZ</displayName>
    <description>Debug MCU APB1 Freeze registe</description>
    <addressOffset>0x8</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>DBG_TIM2_STOP</name>
        <description>DBG_TIM2_STOP</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM3_STOP</name>
        <description>DBG_TIM3 _STOP</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM4_STOP</name>
        <description>DBG_TIM4_STOP</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM5_STOP</name>
        <description>DBG_TIM5_STOP</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM6_STOP</name>
        <description>DBG_TIM6_STOP</description>
        <bitOffset>4</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM7_STOP</name>
        <description>DBG_TIM7_STOP</description>
        <bitOffset>5</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM12_STOP</name>
        <description>DBG_TIM12_STOP</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM13_STOP</name>
        <description>DBG_TIM13_STOP</description>
        <bitOffset>7</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM14_STOP</name>
        <description>DBG_TIM14_STOP</description>
        <bitOffset>8</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_WWDG_STOP</name>
        <description>DBG_WWDG_STOP</description>
        <bitOffset>11</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_IWDEG_STOP</name>
        <description>DBG_IWDEG_STOP</description>
        <bitOffset>12</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_J2C1_SMBUS_TIMEOUT</name>
        <description>DBG_J2C1_SMBUS_TIMEOUT</description>
        <bitOffset>21</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_J2C2_SMBUS_TIMEOUT</name>
        <description>DBG_J2C2_SMBUS_TIMEOUT</description>
        <bitOffset>22</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_J2C3SMBUS_TIMEOUT</name>
        <description>DBG_J2C3SMBUS_TIMEOUT</description>
        <bitOffset>23</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_CAN1_STOP</name>
        <description>DBG_CAN1_STOP</description>
        <bitOffset>25</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_CAN2_STOP</name>
        <description>DBG_CAN2_STOP</description>
        <bitOffset>26</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>DBGMCU_APB2_FZ</name>
    <displayName>DBGMCU_APB2_FZ</displayName>
    <description>Debug MCU APB2 Freeze registe</description>
    <addressOffset>0xC</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>DBG_TIM1_STOP</name>
        <description>TIM1 counter stopped when core is
        halted</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM8_STOP</name>
        <description>TIM8 counter stopped when core is
        halted</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM9_STOP</name>
        <description>TIM9 counter stopped when core is
        halted</description>
        <bitOffset>16</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM10_STOP</name>
        <description>TIM10 counter stopped when core is
        halted</description>
        <bitOffset>17</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DBG_TIM11_STOP</name>
        <description>TIM11 counter stopped when core is
        halted</description>
        <bitOffset>18</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
</registers>
