<description>Flexible static memory controller</description>
<groupName>FSMC</groupName>
<addressBlock>
  <offset>0x0</offset>
  <size>0x400</size>
  <usage>registers</usage>
</addressBlock>
<registers>
  <register>
    <name>BCR1</name>
    <displayName>BCR1</displayName>
    <description>SRAM/NOR-Flash chip-select control register
    1</description>
    <addressOffset>0x0</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x000030D0</resetValue>
    <fields>
      <field>
        <name>CBURSTRW</name>
        <description>CBURSTRW</description>
        <bitOffset>19</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>ASYNCWAIT</name>
        <description>ASYNCWAIT</description>
        <bitOffset>15</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>EXTMOD</name>
        <description>EXTMOD</description>
        <bitOffset>14</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITEN</name>
        <description>WAITEN</description>
        <bitOffset>13</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WREN</name>
        <description>WREN</description>
        <bitOffset>12</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITCFG</name>
        <description>WAITCFG</description>
        <bitOffset>11</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITPOL</name>
        <description>WAITPOL</description>
        <bitOffset>9</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>BURSTEN</name>
        <description>BURSTEN</description>
        <bitOffset>8</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>FACCEN</name>
        <description>FACCEN</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MWID</name>
        <description>MWID</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MTYP</name>
        <description>MTYP</description>
        <bitOffset>2</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MUXEN</name>
        <description>MUXEN</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MBKEN</name>
        <description>MBKEN</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BTR1</name>
    <displayName>BTR1</displayName>
    <description>SRAM/NOR-Flash chip-select timing register
    1</description>
    <addressOffset>0x4</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFFFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>BUSTURN</name>
        <description>BUSTURN</description>
        <bitOffset>16</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BCR2</name>
    <displayName>BCR2</displayName>
    <description>SRAM/NOR-Flash chip-select control register
    2</description>
    <addressOffset>0x8</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x000030D0</resetValue>
    <fields>
      <field>
        <name>CBURSTRW</name>
        <description>CBURSTRW</description>
        <bitOffset>19</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>ASYNCWAIT</name>
        <description>ASYNCWAIT</description>
        <bitOffset>15</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>EXTMOD</name>
        <description>EXTMOD</description>
        <bitOffset>14</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITEN</name>
        <description>WAITEN</description>
        <bitOffset>13</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WREN</name>
        <description>WREN</description>
        <bitOffset>12</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITCFG</name>
        <description>WAITCFG</description>
        <bitOffset>11</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WRAPMOD</name>
        <description>WRAPMOD</description>
        <bitOffset>10</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITPOL</name>
        <description>WAITPOL</description>
        <bitOffset>9</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>BURSTEN</name>
        <description>BURSTEN</description>
        <bitOffset>8</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>FACCEN</name>
        <description>FACCEN</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MWID</name>
        <description>MWID</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MTYP</name>
        <description>MTYP</description>
        <bitOffset>2</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MUXEN</name>
        <description>MUXEN</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MBKEN</name>
        <description>MBKEN</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BTR2</name>
    <displayName>BTR2</displayName>
    <description>SRAM/NOR-Flash chip-select timing register
    2</description>
    <addressOffset>0xC</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFFFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>BUSTURN</name>
        <description>BUSTURN</description>
        <bitOffset>16</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BCR3</name>
    <displayName>BCR3</displayName>
    <description>SRAM/NOR-Flash chip-select control register
    3</description>
    <addressOffset>0x10</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x000030D0</resetValue>
    <fields>
      <field>
        <name>CBURSTRW</name>
        <description>CBURSTRW</description>
        <bitOffset>19</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>ASYNCWAIT</name>
        <description>ASYNCWAIT</description>
        <bitOffset>15</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>EXTMOD</name>
        <description>EXTMOD</description>
        <bitOffset>14</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITEN</name>
        <description>WAITEN</description>
        <bitOffset>13</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WREN</name>
        <description>WREN</description>
        <bitOffset>12</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITCFG</name>
        <description>WAITCFG</description>
        <bitOffset>11</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WRAPMOD</name>
        <description>WRAPMOD</description>
        <bitOffset>10</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITPOL</name>
        <description>WAITPOL</description>
        <bitOffset>9</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>BURSTEN</name>
        <description>BURSTEN</description>
        <bitOffset>8</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>FACCEN</name>
        <description>FACCEN</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MWID</name>
        <description>MWID</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MTYP</name>
        <description>MTYP</description>
        <bitOffset>2</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MUXEN</name>
        <description>MUXEN</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MBKEN</name>
        <description>MBKEN</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BTR3</name>
    <displayName>BTR3</displayName>
    <description>SRAM/NOR-Flash chip-select timing register
    3</description>
    <addressOffset>0x14</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFFFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>BUSTURN</name>
        <description>BUSTURN</description>
        <bitOffset>16</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BCR4</name>
    <displayName>BCR4</displayName>
    <description>SRAM/NOR-Flash chip-select control register
    4</description>
    <addressOffset>0x18</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x000030D0</resetValue>
    <fields>
      <field>
        <name>CBURSTRW</name>
        <description>CBURSTRW</description>
        <bitOffset>19</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>ASYNCWAIT</name>
        <description>ASYNCWAIT</description>
        <bitOffset>15</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>EXTMOD</name>
        <description>EXTMOD</description>
        <bitOffset>14</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITEN</name>
        <description>WAITEN</description>
        <bitOffset>13</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WREN</name>
        <description>WREN</description>
        <bitOffset>12</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITCFG</name>
        <description>WAITCFG</description>
        <bitOffset>11</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WRAPMOD</name>
        <description>WRAPMOD</description>
        <bitOffset>10</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>WAITPOL</name>
        <description>WAITPOL</description>
        <bitOffset>9</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>BURSTEN</name>
        <description>BURSTEN</description>
        <bitOffset>8</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>FACCEN</name>
        <description>FACCEN</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MWID</name>
        <description>MWID</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MTYP</name>
        <description>MTYP</description>
        <bitOffset>2</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>MUXEN</name>
        <description>MUXEN</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>MBKEN</name>
        <description>MBKEN</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BTR4</name>
    <displayName>BTR4</displayName>
    <description>SRAM/NOR-Flash chip-select timing register
    4</description>
    <addressOffset>0x1C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFFFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>BUSTURN</name>
        <description>BUSTURN</description>
        <bitOffset>16</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>PCR2</name>
    <displayName>PCR2</displayName>
    <description>PC Card/NAND Flash control register
    2</description>
    <addressOffset>0x60</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000018</resetValue>
    <fields>
      <field>
        <name>ECCPS</name>
        <description>ECCPS</description>
        <bitOffset>17</bitOffset>
        <bitWidth>3</bitWidth>
      </field>
      <field>
        <name>TAR</name>
        <description>TAR</description>
        <bitOffset>13</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>TCLR</name>
        <description>TCLR</description>
        <bitOffset>9</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ECCEN</name>
        <description>ECCEN</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PWID</name>
        <description>PWID</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>PTYP</name>
        <description>PTYP</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PBKEN</name>
        <description>PBKEN</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PWAITEN</name>
        <description>PWAITEN</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>SR2</name>
    <displayName>SR2</displayName>
    <description>FIFO status and interrupt register
    2</description>
    <addressOffset>0x64</addressOffset>
    <size>0x20</size>
    <resetValue>0x00000040</resetValue>
    <fields>
      <field>
        <name>FEMPT</name>
        <description>FEMPT</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-only</access>
      </field>
      <field>
        <name>IFEN</name>
        <description>IFEN</description>
        <bitOffset>5</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>ILEN</name>
        <description>ILEN</description>
        <bitOffset>4</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IREN</name>
        <description>IREN</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IFS</name>
        <description>IFS</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>ILS</name>
        <description>ILS</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IRS</name>
        <description>IRS</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
    </fields>
  </register>
  <register>
    <name>PMEM2</name>
    <displayName>PMEM2</displayName>
    <description>Common memory space timing register
    2</description>
    <addressOffset>0x68</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFCFCFCFC</resetValue>
    <fields>
      <field>
        <name>MEMHIZx</name>
        <description>MEMHIZx</description>
        <bitOffset>24</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMHOLDx</name>
        <description>MEMHOLDx</description>
        <bitOffset>16</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMWAITx</name>
        <description>MEMWAITx</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMSETx</name>
        <description>MEMSETx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>PATT2</name>
    <displayName>PATT2</displayName>
    <description>Attribute memory space timing register
    2</description>
    <addressOffset>0x6C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFCFCFCFC</resetValue>
    <fields>
      <field>
        <name>ATTHIZx</name>
        <description>ATTHIZx</description>
        <bitOffset>24</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTHOLDx</name>
        <description>ATTHOLDx</description>
        <bitOffset>16</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTWAITx</name>
        <description>ATTWAITx</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTSETx</name>
        <description>ATTSETx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>ECCR2</name>
    <displayName>ECCR2</displayName>
    <description>ECC result register 2</description>
    <addressOffset>0x74</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>ECCx</name>
        <description>ECCx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>PCR3</name>
    <displayName>PCR3</displayName>
    <description>PC Card/NAND Flash control register
    3</description>
    <addressOffset>0x80</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000018</resetValue>
    <fields>
      <field>
        <name>ECCPS</name>
        <description>ECCPS</description>
        <bitOffset>17</bitOffset>
        <bitWidth>3</bitWidth>
      </field>
      <field>
        <name>TAR</name>
        <description>TAR</description>
        <bitOffset>13</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>TCLR</name>
        <description>TCLR</description>
        <bitOffset>9</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ECCEN</name>
        <description>ECCEN</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PWID</name>
        <description>PWID</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>PTYP</name>
        <description>PTYP</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PBKEN</name>
        <description>PBKEN</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PWAITEN</name>
        <description>PWAITEN</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>SR3</name>
    <displayName>SR3</displayName>
    <description>FIFO status and interrupt register
    3</description>
    <addressOffset>0x84</addressOffset>
    <size>0x20</size>
    <resetValue>0x00000040</resetValue>
    <fields>
      <field>
        <name>FEMPT</name>
        <description>FEMPT</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-only</access>
      </field>
      <field>
        <name>IFEN</name>
        <description>IFEN</description>
        <bitOffset>5</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>ILEN</name>
        <description>ILEN</description>
        <bitOffset>4</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IREN</name>
        <description>IREN</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IFS</name>
        <description>IFS</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>ILS</name>
        <description>ILS</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IRS</name>
        <description>IRS</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
    </fields>
  </register>
  <register>
    <name>PMEM3</name>
    <displayName>PMEM3</displayName>
    <description>Common memory space timing register
    3</description>
    <addressOffset>0x88</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFCFCFCFC</resetValue>
    <fields>
      <field>
        <name>MEMHIZx</name>
        <description>MEMHIZx</description>
        <bitOffset>24</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMHOLDx</name>
        <description>MEMHOLDx</description>
        <bitOffset>16</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMWAITx</name>
        <description>MEMWAITx</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMSETx</name>
        <description>MEMSETx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>PATT3</name>
    <displayName>PATT3</displayName>
    <description>Attribute memory space timing register
    3</description>
    <addressOffset>0x8C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFCFCFCFC</resetValue>
    <fields>
      <field>
        <name>ATTHIZx</name>
        <description>ATTHIZx</description>
        <bitOffset>24</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTHOLDx</name>
        <description>ATTHOLDx</description>
        <bitOffset>16</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTWAITx</name>
        <description>ATTWAITx</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTSETx</name>
        <description>ATTSETx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>ECCR3</name>
    <displayName>ECCR3</displayName>
    <description>ECC result register 3</description>
    <addressOffset>0x94</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>ECCx</name>
        <description>ECCx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>PCR4</name>
    <displayName>PCR4</displayName>
    <description>PC Card/NAND Flash control register
    4</description>
    <addressOffset>0xA0</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000018</resetValue>
    <fields>
      <field>
        <name>ECCPS</name>
        <description>ECCPS</description>
        <bitOffset>17</bitOffset>
        <bitWidth>3</bitWidth>
      </field>
      <field>
        <name>TAR</name>
        <description>TAR</description>
        <bitOffset>13</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>TCLR</name>
        <description>TCLR</description>
        <bitOffset>9</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ECCEN</name>
        <description>ECCEN</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PWID</name>
        <description>PWID</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>PTYP</name>
        <description>PTYP</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PBKEN</name>
        <description>PBKEN</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>PWAITEN</name>
        <description>PWAITEN</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>SR4</name>
    <displayName>SR4</displayName>
    <description>FIFO status and interrupt register
    4</description>
    <addressOffset>0xA4</addressOffset>
    <size>0x20</size>
    <resetValue>0x00000040</resetValue>
    <fields>
      <field>
        <name>FEMPT</name>
        <description>FEMPT</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-only</access>
      </field>
      <field>
        <name>IFEN</name>
        <description>IFEN</description>
        <bitOffset>5</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>ILEN</name>
        <description>ILEN</description>
        <bitOffset>4</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IREN</name>
        <description>IREN</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IFS</name>
        <description>IFS</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>ILS</name>
        <description>ILS</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>IRS</name>
        <description>IRS</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
    </fields>
  </register>
  <register>
    <name>PMEM4</name>
    <displayName>PMEM4</displayName>
    <description>Common memory space timing register
    4</description>
    <addressOffset>0xA8</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFCFCFCFC</resetValue>
    <fields>
      <field>
        <name>MEMHIZx</name>
        <description>MEMHIZx</description>
        <bitOffset>24</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMHOLDx</name>
        <description>MEMHOLDx</description>
        <bitOffset>16</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMWAITx</name>
        <description>MEMWAITx</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>MEMSETx</name>
        <description>MEMSETx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>PATT4</name>
    <displayName>PATT4</displayName>
    <description>Attribute memory space timing register
    4</description>
    <addressOffset>0xAC</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFCFCFCFC</resetValue>
    <fields>
      <field>
        <name>ATTHIZx</name>
        <description>ATTHIZx</description>
        <bitOffset>24</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTHOLDx</name>
        <description>ATTHOLDx</description>
        <bitOffset>16</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTWAITx</name>
        <description>ATTWAITx</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ATTSETx</name>
        <description>ATTSETx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>PIO4</name>
    <displayName>PIO4</displayName>
    <description>I/O space timing register 4</description>
    <addressOffset>0xB0</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0xFCFCFCFC</resetValue>
    <fields>
      <field>
        <name>IOHIZx</name>
        <description>IOHIZx</description>
        <bitOffset>24</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>IOHOLDx</name>
        <description>IOHOLDx</description>
        <bitOffset>16</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>IOWAITx</name>
        <description>IOWAITx</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>IOSETx</name>
        <description>IOSETx</description>
        <bitOffset>0</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BWTR1</name>
    <displayName>BWTR1</displayName>
    <description>SRAM/NOR-Flash write timing registers
    1</description>
    <addressOffset>0x104</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x0FFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BWTR2</name>
    <displayName>BWTR2</displayName>
    <description>SRAM/NOR-Flash write timing registers
    2</description>
    <addressOffset>0x10C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x0FFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BWTR3</name>
    <displayName>BWTR3</displayName>
    <description>SRAM/NOR-Flash write timing registers
    3</description>
    <addressOffset>0x114</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x0FFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>BWTR4</name>
    <displayName>BWTR4</displayName>
    <description>SRAM/NOR-Flash write timing registers
    4</description>
    <addressOffset>0x11C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x0FFFFFFF</resetValue>
    <fields>
      <field>
        <name>ACCMOD</name>
        <description>ACCMOD</description>
        <bitOffset>28</bitOffset>
        <bitWidth>2</bitWidth>
      </field>
      <field>
        <name>DATLAT</name>
        <description>DATLAT</description>
        <bitOffset>24</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>CLKDIV</name>
        <description>CLKDIV</description>
        <bitOffset>20</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>DATAST</name>
        <description>DATAST</description>
        <bitOffset>8</bitOffset>
        <bitWidth>8</bitWidth>
      </field>
      <field>
        <name>ADDHLD</name>
        <description>ADDHLD</description>
        <bitOffset>4</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
      <field>
        <name>ADDSET</name>
        <description>ADDSET</description>
        <bitOffset>0</bitOffset>
        <bitWidth>4</bitWidth>
      </field>
    </fields>
  </register>
</registers>
