<description>Hash processor</description>
<groupName>HASH</groupName>
<baseAddress>0x50060400</baseAddress>
<addressBlock>
  <offset>0x0</offset>
  <size>0x400</size>
  <usage>registers</usage>
</addressBlock>
<registers>
  <register>
    <name>CR</name>
    <displayName>CR</displayName>
    <description>control register</description>
    <addressOffset>0x0</addressOffset>
    <size>0x20</size>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>LKEY</name>
        <description>Long key selection</description>
        <bitOffset>16</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>DINNE</name>
        <description>DIN not empty</description>
        <bitOffset>12</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-only</access>
      </field>
      <field>
        <name>NBW</name>
        <description>Number of words already
        pushed</description>
        <bitOffset>8</bitOffset>
        <bitWidth>4</bitWidth>
        <access>read-only</access>
      </field>
      <field>
        <name>ALGO</name>
        <description>Algorithm selection</description>
        <bitOffset>7</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>MODE</name>
        <description>Mode selection</description>
        <bitOffset>6</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>DATATYPE</name>
        <description>Data type selection</description>
        <bitOffset>4</bitOffset>
        <bitWidth>2</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>DMAE</name>
        <description>DMA enable</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>INIT</name>
        <description>Initialize message digest
        calculation</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
        <access>write-only</access>
      </field>
    </fields>
  </register>
  <register>
    <name>DIN</name>
    <displayName>DIN</displayName>
    <description>data input register</description>
    <addressOffset>0x4</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>DATAIN</name>
        <description>Data input</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>STR</name>
    <displayName>STR</displayName>
    <description>start register</description>
    <addressOffset>0x8</addressOffset>
    <size>0x20</size>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>DCAL</name>
        <description>Digest calculation</description>
        <bitOffset>8</bitOffset>
        <bitWidth>1</bitWidth>
        <access>write-only</access>
      </field>
      <field>
        <name>NBLW</name>
        <description>Number of valid bits in the last word of
        the message</description>
        <bitOffset>0</bitOffset>
        <bitWidth>5</bitWidth>
        <access>read-write</access>
      </field>
    </fields>
  </register>
  <register>
    <name>HR0</name>
    <displayName>HR0</displayName>
    <description>digest registers</description>
    <addressOffset>0xC</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>H0</name>
        <description>H0</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>HR1</name>
    <displayName>HR1</displayName>
    <description>digest registers</description>
    <addressOffset>0x10</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>H1</name>
        <description>H1</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>HR2</name>
    <displayName>HR2</displayName>
    <description>digest registers</description>
    <addressOffset>0x14</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>H2</name>
        <description>H2</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>HR3</name>
    <displayName>HR3</displayName>
    <description>digest registers</description>
    <addressOffset>0x18</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>H3</name>
        <description>H3</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>HR4</name>
    <displayName>HR4</displayName>
    <description>digest registers</description>
    <addressOffset>0x1C</addressOffset>
    <size>0x20</size>
    <access>read-only</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>H4</name>
        <description>H4</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>IMR</name>
    <displayName>IMR</displayName>
    <description>interrupt enable register</description>
    <addressOffset>0x20</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>DCIE</name>
        <description>Digest calculation completion interrupt
        enable</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
      <field>
        <name>DINIE</name>
        <description>Data input interrupt
        enable</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>SR</name>
    <displayName>SR</displayName>
    <description>status register</description>
    <addressOffset>0x24</addressOffset>
    <size>0x20</size>
    <resetValue>0x00000001</resetValue>
    <fields>
      <field>
        <name>BUSY</name>
        <description>Busy bit</description>
        <bitOffset>3</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-only</access>
      </field>
      <field>
        <name>DMAS</name>
        <description>DMA Status</description>
        <bitOffset>2</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-only</access>
      </field>
      <field>
        <name>DCIS</name>
        <description>Digest calculation completion interrupt
        status</description>
        <bitOffset>1</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
      <field>
        <name>DINIS</name>
        <description>Data input interrupt
        status</description>
        <bitOffset>0</bitOffset>
        <bitWidth>1</bitWidth>
        <access>read-write</access>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR0</name>
    <displayName>CSR0</displayName>
    <description>context swap registers</description>
    <addressOffset>0xF8</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR0</name>
        <description>CSR0</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR1</name>
    <displayName>CSR1</displayName>
    <description>context swap registers</description>
    <addressOffset>0xFC</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR1</name>
        <description>CSR1</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR2</name>
    <displayName>CSR2</displayName>
    <description>context swap registers</description>
    <addressOffset>0x100</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR2</name>
        <description>CSR2</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR3</name>
    <displayName>CSR3</displayName>
    <description>context swap registers</description>
    <addressOffset>0x104</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR3</name>
        <description>CSR3</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR4</name>
    <displayName>CSR4</displayName>
    <description>context swap registers</description>
    <addressOffset>0x108</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR4</name>
        <description>CSR4</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR5</name>
    <displayName>CSR5</displayName>
    <description>context swap registers</description>
    <addressOffset>0x10C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR5</name>
        <description>CSR5</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR6</name>
    <displayName>CSR6</displayName>
    <description>context swap registers</description>
    <addressOffset>0x110</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR6</name>
        <description>CSR6</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR7</name>
    <displayName>CSR7</displayName>
    <description>context swap registers</description>
    <addressOffset>0x114</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR7</name>
        <description>CSR7</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR8</name>
    <displayName>CSR8</displayName>
    <description>context swap registers</description>
    <addressOffset>0x118</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR8</name>
        <description>CSR8</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR9</name>
    <displayName>CSR9</displayName>
    <description>context swap registers</description>
    <addressOffset>0x11C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR9</name>
        <description>CSR9</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR10</name>
    <displayName>CSR10</displayName>
    <description>context swap registers</description>
    <addressOffset>0x120</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR10</name>
        <description>CSR10</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR11</name>
    <displayName>CSR11</displayName>
    <description>context swap registers</description>
    <addressOffset>0x124</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR11</name>
        <description>CSR11</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR12</name>
    <displayName>CSR12</displayName>
    <description>context swap registers</description>
    <addressOffset>0x128</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR12</name>
        <description>CSR12</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR13</name>
    <displayName>CSR13</displayName>
    <description>context swap registers</description>
    <addressOffset>0x12C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR13</name>
        <description>CSR13</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR14</name>
    <displayName>CSR14</displayName>
    <description>context swap registers</description>
    <addressOffset>0x130</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR14</name>
        <description>CSR14</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR15</name>
    <displayName>CSR15</displayName>
    <description>context swap registers</description>
    <addressOffset>0x134</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR15</name>
        <description>CSR15</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR16</name>
    <displayName>CSR16</displayName>
    <description>context swap registers</description>
    <addressOffset>0x138</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR16</name>
        <description>CSR16</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR17</name>
    <displayName>CSR17</displayName>
    <description>context swap registers</description>
    <addressOffset>0x13C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR17</name>
        <description>CSR17</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR18</name>
    <displayName>CSR18</displayName>
    <description>context swap registers</description>
    <addressOffset>0x140</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR18</name>
        <description>CSR18</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR19</name>
    <displayName>CSR19</displayName>
    <description>context swap registers</description>
    <addressOffset>0x144</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR19</name>
        <description>CSR19</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR20</name>
    <displayName>CSR20</displayName>
    <description>context swap registers</description>
    <addressOffset>0x148</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR20</name>
        <description>CSR20</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR21</name>
    <displayName>CSR21</displayName>
    <description>context swap registers</description>
    <addressOffset>0x14C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR21</name>
        <description>CSR21</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR22</name>
    <displayName>CSR22</displayName>
    <description>context swap registers</description>
    <addressOffset>0x150</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR22</name>
        <description>CSR22</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR23</name>
    <displayName>CSR23</displayName>
    <description>context swap registers</description>
    <addressOffset>0x154</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR23</name>
        <description>CSR23</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR24</name>
    <displayName>CSR24</displayName>
    <description>context swap registers</description>
    <addressOffset>0x158</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR24</name>
        <description>CSR24</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR25</name>
    <displayName>CSR25</displayName>
    <description>context swap registers</description>
    <addressOffset>0x15C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR25</name>
        <description>CSR25</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR26</name>
    <displayName>CSR26</displayName>
    <description>context swap registers</description>
    <addressOffset>0x160</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR26</name>
        <description>CSR26</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR27</name>
    <displayName>CSR27</displayName>
    <description>context swap registers</description>
    <addressOffset>0x164</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR27</name>
        <description>CSR27</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR28</name>
    <displayName>CSR28</displayName>
    <description>context swap registers</description>
    <addressOffset>0x168</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR28</name>
        <description>CSR28</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR29</name>
    <displayName>CSR29</displayName>
    <description>context swap registers</description>
    <addressOffset>0x16C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR29</name>
        <description>CSR29</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR30</name>
    <displayName>CSR30</displayName>
    <description>context swap registers</description>
    <addressOffset>0x170</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR30</name>
        <description>CSR30</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR31</name>
    <displayName>CSR31</displayName>
    <description>context swap registers</description>
    <addressOffset>0x174</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR31</name>
        <description>CSR31</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR32</name>
    <displayName>CSR32</displayName>
    <description>context swap registers</description>
    <addressOffset>0x178</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR32</name>
        <description>CSR32</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR33</name>
    <displayName>CSR33</displayName>
    <description>context swap registers</description>
    <addressOffset>0x17C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR33</name>
        <description>CSR33</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR34</name>
    <displayName>CSR34</displayName>
    <description>context swap registers</description>
    <addressOffset>0x180</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR34</name>
        <description>CSR34</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR35</name>
    <displayName>CSR35</displayName>
    <description>context swap registers</description>
    <addressOffset>0x184</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR35</name>
        <description>CSR35</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR36</name>
    <displayName>CSR36</displayName>
    <description>context swap registers</description>
    <addressOffset>0x188</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR36</name>
        <description>CSR36</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR37</name>
    <displayName>CSR37</displayName>
    <description>context swap registers</description>
    <addressOffset>0x18C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR37</name>
        <description>CSR37</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR38</name>
    <displayName>CSR38</displayName>
    <description>context swap registers</description>
    <addressOffset>0x190</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR38</name>
        <description>CSR38</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR39</name>
    <displayName>CSR39</displayName>
    <description>context swap registers</description>
    <addressOffset>0x194</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR39</name>
        <description>CSR39</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR40</name>
    <displayName>CSR40</displayName>
    <description>context swap registers</description>
    <addressOffset>0x198</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR40</name>
        <description>CSR40</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR41</name>
    <displayName>CSR41</displayName>
    <description>context swap registers</description>
    <addressOffset>0x19C</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR41</name>
        <description>CSR41</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR42</name>
    <displayName>CSR42</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1A0</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR42</name>
        <description>CSR42</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR43</name>
    <displayName>CSR43</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1A4</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR43</name>
        <description>CSR43</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR44</name>
    <displayName>CSR44</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1A8</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR44</name>
        <description>CSR44</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR45</name>
    <displayName>CSR45</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1AC</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR45</name>
        <description>CSR45</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR46</name>
    <displayName>CSR46</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1B0</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR46</name>
        <description>CSR46</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR47</name>
    <displayName>CSR47</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1B4</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR47</name>
        <description>CSR47</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR48</name>
    <displayName>CSR48</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1B8</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR48</name>
        <description>CSR48</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR49</name>
    <displayName>CSR49</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1BC</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR49</name>
        <description>CSR49</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
  <register>
    <name>CSR50</name>
    <displayName>CSR50</displayName>
    <description>context swap registers</description>
    <addressOffset>0x1C0</addressOffset>
    <size>0x20</size>
    <access>read-write</access>
    <resetValue>0x00000000</resetValue>
    <fields>
      <field>
        <name>CSR50</name>
        <description>CSR50</description>
        <bitOffset>0</bitOffset>
        <bitWidth>32</bitWidth>
      </field>
    </fields>
  </register>
</registers>
